spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mongodb:
    uri: ${MONGO_URI}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USER}
      password: ${REDIS_PASS}

app:
  cors:
    allowed-origins: ${RESEND_URL}

resend:
  api-key: ${RESEND_API_KEY}
  from-email: ${RESEND_FROM_EMAIL}
  base-url: ${RESEND_URL}

jwt:
  secret: ${JWT_SECRET}
  access-exp-minutes: 30
  refresh-exp-days: 14